Repository thoth-station/zuul-config, pull requests merged in 2018-10, with the labels that each got.

#14 using a SA to access a project to run pods in that
  nodepool/thoth.yaml
Labels: approved, size/S

#15 node pool name needs to be openshift project name
  nodepool/thoth.yaml
Labels: approved, size/XS

#16 switching to zuul-infra based job pods
  nodepool/thoth.yaml
Labels: size/XS

#17 changed the project
  nodepool/thoth.yaml
Labels: size/XS

#18 renamed a few things and added thoth-pytest pod
  nodepool/thoth.yaml
Labels: size/S

#19 fixed a typo
  nodepool/thoth.yaml
Labels: size/XS

#20 adding amun-client repository
  zuul/amun-client.yaml
Labels: size/XS

#22 added thoth-metrics project
  zuul/thoth-metrics.yaml
Labels: size/XS

#23 base-openshift-pod: use logclassify_ara_database
  roles/log-classify/defaults/main.yaml
  roles/log-classify/tasks/run.yaml
  zuul.d/_jobs-openshift.yaml
Labels: size/S
