Repository thoth-station/zuul-config, pull requests merged in 2019-05, with the labels that each got.

#54 Add invectio to monitored repos
  zuul/invectio.yaml
Labels: approved, size/XS

#56 update build-trigger playbook to use parameter input
  playbooks/thoth-openshift-trigger-build/run.yaml
Labels: approved, size/S

#55 preparing migration to thoth-zuul-psi
  nodepool/thoth.yaml
Labels: approved, size/S

#58 Add AICoE/workshop-coding-best-practices for bootcamp
  zuul/workshop-coding-best-practices.yaml
Labels: needs-rebase, size/XS

#59 Revert "preparing migration to thoth-zuul-psi"
  nodepool/thoth.yaml
Labels: size/S

#61 added PSI cluster nodepool config
  nodepool/thoth.yaml
Labels: size/M

#62 Update trigger build job with a default cluster parameter
  playbooks/thoth-openshift-trigger-build/run.yaml
Labels: approved, size/XS

#60 Add trigger build job instruction for new trigger build job API
  zuul.d/README
  zuul.d/README.md
Labels: approved, needs-rebase, size/M
