Repository thoth-station/zuul-config, pull requests merged in 2019-09, with the labels that each got.

#80 Added prometheus-scraper config file
  zuul/prometheus-scraper.yaml
Labels: approved, size/XS

#81 Added prometheus-anomaly-detector config file
  zuul/prometheus-anomaly-detector.yaml
Labels: approved, size/XS

#82 Added prometheus-anomaly-detector-legacy config file
  zuul/prometheus-anomaly-detector-legacy.yaml
Labels: approved, size/XS

#83 archived osiris projects
  zuul/osiris-build-observer.yaml
  zuul/osiris.yaml
Labels: approved, size/S

#85 zuul integration in thoth-station/workflows
  zuul/workflows.yaml
Labels: approved, size/XS

#84 update on zuul integration
  README.md
Labels: approved, size/M
