Repository thoth-station/zuul-config, pull requests merged in 2019-02, with the labels that each got.

#36 Exclude unprotected branch for the config projects
  zuul/_main.yaml
Labels: size/XS

#37 Exclude unprotected branch for the config resources
  resources/_internal.yaml
Labels: size/XS

#38 Remove zuul configuration for internal resource
  zuul/_main.yaml
Labels: size/S

#39 added build-watcher repo
  zuul/build-watcher.yaml
Labels: size/XS

#40 adding init-job and graph-sync-scheduler projects
  zuul/graph-sync-scheduler.yaml
  zuul/init-job.yaml
Labels: size/S

#42 this have been moved in here from zuul-test-jobs
  zuul.d/webhook-secrets.yaml
Labels: size/S

#41 reorged to respect https://review.openstack.org/#/c/632566/
  playbooks/thoth-openshift-trigger-build/run.yaml
  zuul.d/thoth-openshift.yaml
  zuul.d/webhook-secrets.yaml
Labels: size/M, size/S

#43 moving it to -config project
  zuul.d/jobs-upload-pypi-thoth.yaml
  zuul.d/secret_pypi_sesheta.yaml
Labels: size/S
