Repository thoth-station/zuul-config, pull requests merged in 2019-07, with the labels that each got.

#74 Add standard GitHub templates and CODEOWNERS
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, size/M

#73 Add package-analyzer
  zuul/package-analyzer.yaml
Labels: approved, size/M, size/XS

#75 Modified the names to standard convention
  zuul/build-analyzers.yaml
Labels: approved, size/XS
