Repository thoth-station/zuul-config, pull requests merged in 2019-06, with the labels that each got.

#63 added digests-fetcher project
  zuul/digests-fetcher.yaml
Labels: size/XS

#64 Fix up the content in zuul-job usage
  README.md
  zuul.d/README.md
Labels: approved, size/M, size/S

#65 Fix up indentation in Readme code
  README.md
Labels: approved, size/XS

#66 Fix the Ansible playbook for getting bad request error
  playbooks/thoth-openshift-trigger-build/run.yaml
Labels: approved, size/XS

#67 updated nodepool to use thoth-ops:v0.12.0
  nodepool/thoth.yaml
Labels: size/S, size/XS

#68 zuul job to set WIP label on PR
  playbooks/github-wip/run.yaml
  roles/check-github-pr-is-wip/README.rst
  roles/check-github-pr-is-wip/files/github_wip.py
  roles/check-github-pr-is-wip/tasks/main.yaml
  zuul.d/thoth-openshift.yaml
Labels: size/L

#69 added project template
  zuul.d/project-templates.yaml
  zuul.d/thoth-openshift.yaml
Labels: size/S

#71 adding integration-tests project
  zuul/integration-tests.yaml
Labels: size/XS
