Repository thoth-station/zuul-config, pull requests merged in 2020-01, with the labels that each got.

#99 added thoth-ops token as a secret for srcops-testing
  zuul.d/thoth-ops-secrets.yaml
Labels: size/S

#100 moved to zuul-config repo
  playbooks/thoth-openshift-apply-template/run.yaml
  zuul.d/thoth-openshift.yaml
  zuul.d/thoth-ops-secrets.yaml
Labels: size/M

#101 providing server url for `oc login`
  playbooks/thoth-openshift-apply-template/run.yaml
Labels: size/XS

#102 as we want to expand env var, we need to use shell rather than command
  playbooks/thoth-openshift-apply-template/run.yaml
Labels: size/XS

#104 Add thoth-station/ash-api
  zuul/ash-api.yaml
Labels: approved, size/XS

#103 Add thoth-station/stub-api to Zuul config
  zuul/stub-api.yaml
Labels: approved, size/XS
