Repository thoth-station/zuul-config, pull requests merged in 2020-02, with the labels that each got.

#105 Create package-update-job.yaml
  zuul/package-update-job.yaml
Labels: approved, size/XS

#107 Update upstream zuul-jobs to the new url
  resources/_internal.yaml
  zuul.d/_jobs-base.yaml
  zuul.d/_jobs-openshift.yaml
  zuul.d/thoth-openshift.yaml
Labels: approved, size/S

#108 Add new virt_images nodepool configuration
  nodepool/virt_images/README.md
  nodepool/virt_images/cloud-centos-8.yaml
  nodepool/virt_images/cloud-fedora-rawhide.yaml
  nodepool/virt_images/roles/base-appliance/tasks/main.yaml
  nodepool/virt_images/roles/base-cleanup/defaults/main.yaml
  nodepool/virt_images/roles/base-cleanup/tasks/main.yaml
  nodepool/virt_images/roles/base-customize/defaults/main.yaml
  nodepool/virt_images/roles/base-customize/tasks/main.yaml
  nodepool/virt_images/roles/base-finalize/defaults/main.yaml
  nodepool/virt_images/roles/base-finalize/tasks/main.yaml
  nodepool/virt_images/roles/base-install-packages/defaults/main.yaml
  nodepool/virt_images/roles/base-install-packages/tasks/main.yaml
  nodepool/virt_images/roles/base/defaults/main.yaml
  nodepool/virt_images/roles/base/tasks/main.yaml
  nodepool/virt_images/roles/discover-rawhide/defaults/main.yaml
  nodepool/virt_images/roles/discover-rawhide/tasks/main.yaml
  nodepool/virt_images/roles/network-config/defaults/main.yaml
  nodepool/virt_images/roles/network-config/tasks/main.yaml
  nodepool/virt_images/roles/sshd-config/defaults/main.yaml
  nodepool/virt_images/roles/sshd-config/files/sshd_config
  nodepool/virt_images/roles/sshd-config/tasks/main.yaml
  nodepool/virt_images/roles/zuul-user/defaults/main.yaml
  nodepool/virt_images/roles/zuul-user/tasks/main.yaml
Labels: approved, size/L

#109 zuul: enable reporting the build page url
  resources/_internal.yaml
Labels: size/XS

#110 config-check: fix the sf gateway_url
  zuul.d/_jobs-base.yaml
Labels: size/XS

#112 config-check: update the job playbook
  playbooks/config/check.yaml
Labels: size/M

#113 config-update: fix fqdn too
  zuul.d/_secret_install_server.yaml
Labels: approved, size/XS

#111 base: add generate-zuul-manifest to post run
  playbooks/base/post.yaml
Labels: approved, size/XS

#106 Add thoth-station/s2i repository
  zuul/s2i.yaml
Labels: approved, size/XS

#114 support aicoe mlperf-tekton
  zuul/mlperf-tekton.yaml
Labels: approved, size/XS

#115 Add thoth-station/micropipenv
  zuul/micropipenv.yaml
Labels: approved, size/XS

#116 Add thoth-station/template-project
  zuul/template-project.yaml
Labels: approved, size/XS

#117 Add thoth-station/solver-error-classfier
  zuul/solver-error-classfier.yaml
Labels: approved, size/XS
